-- MySQL Script generated by MySQL Workbench
-- Sat May 30 16:15:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema binder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema binder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `binder` ;
USE `binder` ;

-- -----------------------------------------------------
-- Table `binder`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `binder`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `recovery` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`, `username`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `binder`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `binder`.`article` (
  `idArticle` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastEdit` DATETIME NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  `author` INT(11) NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_articles_users` (`author` ASC),
  CONSTRAINT `fk_articles_users`
    FOREIGN KEY (`author`)
    REFERENCES `binder`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `binder`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `binder`.`image` (
  `idimage` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idimage`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `binder`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `binder`.`section` (
  `idSection` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSection`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `binder`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `binder`.`publication` (
  `idPublication` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `content` INT(11) NOT NULL,
  `preview` INT(11) NULL DEFAULT '0',
  `title` TEXT NOT NULL,
  `idSection` INT(11) NOT NULL,
  PRIMARY KEY (`idPublication`),
  INDEX `fk_publication_articles1` (`content` ASC),
  INDEX `fk_publication_images1` (`preview` ASC),
  INDEX `fk_publication_section1_idx` (`idSection` ASC),
  CONSTRAINT `fk_publication_articles`
    FOREIGN KEY (`content`)
    REFERENCES `binder`.`article` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_images1`
    FOREIGN KEY (`preview`)
    REFERENCES `binder`.`image` (`idimage`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publication_section1`
    FOREIGN KEY (`idSection`)
    REFERENCES `binder`.`section` (`idSection`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `binder`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `binder`.`comment` (
  `idcomment` INT(11) NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(45) NULL DEFAULT NULL,
  `Text` MEDIUMTEXT NULL DEFAULT NULL,
  `publication_id` INT(11) NOT NULL,
  `publication_content` INT(11) NOT NULL,
  `date` DATETIME NOT NULL COMMENT 'date of comment',
  `publication_idPublication` INT(11) NOT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comments_publication1` (`publication_id` ASC, `publication_content` ASC),
  INDEX `fk_comments_publication1_idx` (`publication_idPublication` ASC),
  CONSTRAINT `fk_comments_publication1`
    FOREIGN KEY (`publication_idPublication`)
    REFERENCES `binder`.`publication` (`idPublication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `binder`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `binder`.`tag` (
  `idTag` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(56) NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB
AUTO_INCREMENT = 92
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `binder`.`tag_has_publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `binder`.`tag_has_publication` (
  `tag_idTag` INT(11) NOT NULL,
  `publication_idPublication` INT(11) NOT NULL,
  PRIMARY KEY (`tag_idTag`, `publication_idPublication`),
  INDEX `fk_tag_has_publication_publication1_idx` (`publication_idPublication` ASC),
  INDEX `fk_tag_has_publication_tag1_idx` (`tag_idTag` ASC),
  CONSTRAINT `fk_tag_has_publication_publication1`
    FOREIGN KEY (`publication_idPublication`)
    REFERENCES `binder`.`publication` (`idPublication`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_has_publication_tag1`
    FOREIGN KEY (`tag_idTag`)
    REFERENCES `binder`.`tag` (`idTag`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `binder`.`section`(Name) VALUES('Generic');
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
